### ISSUE TITLE
Non-js imports are not to be watched

### ISSUE THREAD

**Issue by droooney** [rollup/rollup-watch#23]
I've noticed this issue working with pug and less plugins. `@import`'s in less and `include`'s in pug don't seem to be watched. If I change any of the less or pug files that are directly imported in js file the watch process reflects but once I change some less file I import in this less file (or include a pug file) the watch process doesn't seem to react in any way. For example:

``` less
// mixins.less

.hidden {
  display: none;
}



// main.less

@import './mixins';

body {
  .hidden();
}
```

or in pug:

``` pug
//- mixins.pug

mixin input(name)
  input(name=name)



//- main.pug

include ./mixins

form
  +input('email')
```

When you have a lot of mixins it's pretty annoying and watching files using rollup-watch doesn't seem to be very useful. Can this even be solved?
